distributable:
  url: https://github.com/ethereum/solidity/releases/download//v{{version}}/solidity_{{version}}.tar.gz

versions:
  - 0.8.17

provides:
  - bin/solc

interprets:
  - .sol

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    cmake.org: 3
    freedesktop.org/pkg-config: ^0.29
    git-scm.org: 2
  working-directory: solidity_0.8.17
  script: |
    ./scripts/build.sh
  test:
    make test

test:
  script: |
    solc --help