distributable:
  url: https://boostorg.jfrog.io/artifactory/main/release/{{ version }}/source/boost_1_80_0.tar.gz
  strip-components: 1

versions:
  - 1.80.0

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    ./bootstrap.sh --prefix={{ prefix }}
    ./b2 install --prefix={{ prefix }}

test:
  script: true  #FIXME